version: "3"
services:
        db_mysql:
                image: "mysql:8.0"
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_USER: dvwa
                        MYSQL_PASSWORD: p@ssw0rd
                container_name: db_mysql
                ports:
                        - "3306:3306"
                networks:
                        dvwa_modsecurity:
                                ipv4_address: 192.168.0.3
       
        website_dvwa:
                build:
                        context:
                                ./website_dvwa/
                environment:
                        DB_USER: dvwa
                        DB_PASSWORD: p@ssw0rd
                        DB_SERVER: 192.168.0.3
                        DB_PORT: 3306
                        DB_DATABASE: dvwa
                        DVWA_SEC_LEVEL: low
                ports:
                        - "8080:80"
                container_name: dvwa
                image: "18uahmad/dvwa"
                networks: 
                        dvwa_modsecurity:
                                ipv4_address: 192.168.0.5

networks:
        dvwa_modsecurity:
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.0.0/24

