version: "3"
services:
        db_mysql:
                image: "mysql:8.0"
                environment:
                        MYSQL_ALLOW_EMPTY_PASSWORD: 1
                        MYSQL_USER: dvwa
                        MYSQL_PASSWORD: dvwa
                        MYSQL_DATABASE: dvwa
                container_name: db_mysql
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - "3306:3306"
                networks:
                        - net
       
        website_dvwa:
                build:
                        context:
                                ./website_dvwa/
                environment:
                        DB_USER: dvwa
                        DB_PASSWORD: dvwa
                        DB_SERVER: db_mysql
                        DB_PORT: 3306
                        DB_DATABASE: dvwa
                        DVWA_SEC_LEVEL: low
                ports:
                        - "8080:80"
                container_name: dvwa
                image: "18uahmad/dvwa"
                networks: 
                        - net
                    
networks:
        net:
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.0.0/24
