#!/bin/bash
mysql -e "CREATE DATABASE $DB_DATABASE;"
mysql -e "CREATE USER '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD';"
mysql -e "GRANT ALL PRIVELIGES ON $DB_DATABASE.* to '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASWORD';"
