version: "3"
services:
        db_mysql:
                image: "mysql:8.0"
                environment:
                        MYSQL_ALLOW_EMPTY_PASSWORD: 1
                        MYSQL_USER: dvwa
                        MYSQL_PASSWORD: dvwa
                        MYSQL_DATABASE: dvwa
                container_name: db_mysql
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - "3306:3306"
                networks:
                        - net
       
        website_dvwa:
                build:
                        context:
                                ./website_dvwa/
                environment:
                        DB_USER: dvwa
                        DB_PASSWORD: dvwa
                        DB_SERVER: db_mysql
                        DB_PORT: 3306
                        DB_DATABASE: dvwa
                        DVWA_SEC_LEVEL: impossible
                container_name: dvwa
                ports:
                        - "1234:80"
                networks: 
                        - net
        modsecurity:
                image: owasp/modsecurity-crs:3.3.2-apache
                environment:
                        BACKEND: http://dvwa:80
                        PROXY: 1
                        MODSEC_AUDIT_LOG: /var/log/modsec_audit.log
                ports:
                        - "80:80"
                networks:
                        - net
                volumes:
                        - ~/modsec_logs/:/var/log/
                container_name: modsec
networks:
        net:
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.0.0/24
